package com.school.teacherarchivesystem.enums;
public enum ActionType { LOGIN, LOGIN_FAILED, FORGOT_PASSWORD, CREATE_ARCHIVE, UPDATE_ARCHIVE, DELETE_ARCHIVE, REVIEW_ARCHIVE, RUN_SCORING, ACTIVATE_TEMPLATE, CREATE_TEMPLATE, EXPORT_RESULT, EXPORT_DATA, CREATE_USER, UPDATE_USER, IMPORT_USER, EXPORT_TEMPLATE, CHANGE_PASSWORD, CREATE_BACKUP, RESTORE_BACKUP }
